# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
# data:
#   nginx.conf: |
#     events {}

#     http {
#         upstream pricedrop {
#             ip_hash;
#             server pricedrop-web:8080;
#         }

#         server {
#             listen 8080;

#             location / {
#                 proxy_pass http://pricedrop;
#             }
#         }
#     }

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-lb
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx-lb
#   template:
#     metadata:
#       labels:
#         app: nginx-lb
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:latest
#           ports:
#             - containerPort: 8080
#           volumeMounts:
#             - name: nginx-config-volume
#               mountPath: /etc/nginx/nginx.conf
#               subPath: nginx.conf
#       volumes:
#         - name: nginx-config-volume
#           configMap:
#             name: nginx-config

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: ClusterIP # No external exposure, use port-forwarding
#   selector:
#     app: nginx-lb
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
        upstream pricedrop {
            ip_hash;
            server pricedrop-web:8080;
        }

        server {
            listen 8080;

            location / {
                proxy_pass http://pricedrop;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_connect_timeout 60s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;

                proxy_redirect off;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-lb
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # nodePort: 8080 # Ensure your cluster allows this nodePort
