apiVersion: v1
kind: Pod
metadata:
  name: pricedrop
  labels:
    name: pricedrop
spec:
  containers:
    - name: pricedrop
      image: satya4236/pricedrop:1
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
  imagePullSecrets:
    - name: docker-hub-secret
