apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pricedrop-rs
  labels:
    name: pricedrop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pricedrop-web
  template:
    metadata:
      labels:
        app: pricedrop-web
    spec:
      containers:
        - name: webapp
          image: satya4236/pricedrop:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      imagePullSecrets:
        - name: docker-hub-secret
